version: '3'

services:
  emdnode0:
    container_name: emdnode0
    image: "emoney/emdnode"
    ports:
      - "26656-26657:26656-26657"
    environment:
      - ID=0
      - LOG=${LOG:-emd.log}
#      - LOGLEVEL=*:info
    volumes:
      - ./build:/emoney:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  emdnode1:
    container_name: emdnode1
    image: "emoney/emdnode"
    ports:
      - "26659-26660:26656-26657"
    environment:
      - ID=1
      - LOG=${LOG:-emd.log}
#      - LOGLEVEL=*:info
    volumes:
      - ./build:/emoney:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  emdnode2:
    container_name: emdnode2
    image: "emoney/emdnode"
    environment:
      - ID=2
      - LOG=${LOG:-emd.log}
#      - LOGLEVEL=*:info
    ports:
      - "26661-26662:26656-26657"
    volumes:
      - ./build:/emoney:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.4

  emdnode3:
    container_name: emdnode3
    image: "emoney/emdnode"
    environment:
      - ID=3
      - LOG=${LOG:-emd.log}
#      - LOGLEVEL=*:info
    ports:
      - "26663-26664:26656-26657"
    volumes:
      - ./build:/emoney:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.5

  rest-server:
    container_name: rest-serve
    image: "emoney/emdnode" # TODO (reviewer) : rest server is included into the emd binary. enable rest (api) via `app.toml`
    environment:
      - NODE=http://emdnode0:26657
    ports:
      - "1317:1317"
    volumes:
      - ./build:/emoney:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.128

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.168.10.0/16

