version: '3'

services:
  gaiadnode0:
    container_name: gaiadnode0
    image: "tendermint/gaiadnode"
    ports:
      - "26556-26557:26556-26557" # peer-rpc
      - "9091:9091" # grpc
      - "6061:6061" # profiling
    environment:
      - ID=0
      - LOG=${LOG:-gaiad.log}
    logging:
      options:
        # 10 Megabytes max for log
        max-size: "10m"
        # keep 2 rotated log files
        max-file: "2"
    #      - LOGLEVEL=*:info
    volumes:
      - ../../../build:/gaiad:Z
    networks:
      localnet:
        ipv4_address: 192.168.11.2

  gaiadnode1:
    container_name: gaiadnode1
    image: "tendermint/gaiadnode"
    ports:
      - "26559-26560:26556-26557"
    environment:
      - ID=1
      - LOG=${LOG:-gaiad.log}
    volumes:
      - ../../../build:/gaiad:Z
    networks:
      localnet:
        ipv4_address: 192.168.11.3

  gaiadnode2:
    container_name: gaiadnode2
    image: "tendermint/gaiadnode"
    environment:
      - ID=2
      - LOG=${LOG:-gaiad.log}
    ports:
      - "26561-26562:26556-26557"
    volumes:
      - ../../../build:/gaiad:Z
    networks:
      localnet:
        ipv4_address: 192.168.11.4

  gaiadnode3:
    container_name: gaiadnode3
    image: "tendermint/gaiadnode"
    environment:
      - ID=3
      - LOG=${LOG:-gaiad.log}
    ports:
      - "26563-26564:26556-26557"
    volumes:
      - ../../../build:/gaiad:Z
    networks:
      localnet:
        ipv4_address: 192.168.11.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        -
          subnet: 192.168.11.0/24 # 254 hosts
